name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  checks:
    runs-on: ubuntu-24.04
    env:
      IMAGE: ghcr.io/chrisgavin/ipman
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build
        run: docker build --target=build .
      - name: Test
        run: docker build --target=test .
      - name: Build Docker Image
        run: docker build --tag "ipman" .
      - name: Registry Login
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: github-actions
          password: ${{ github.token }}
      - name: Push Docker Image
        if: ${{ github.event_name == 'push' }}
        run: |
          docker tag "ipman" "$IMAGE:$GITHUB_SHA"
          docker push "$IMAGE:$GITHUB_SHA"
      - name: Push Latest Docker Image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          docker tag "ipman" "$IMAGE:latest"
          docker push "$IMAGE:latest"
